name: Upload Apk CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app-apk
    - run: ./gradlew uploadApk


