name: Upload Apk CI

on:
  workflow_dispatch:

# 注意：您只能下载在同一工作流程运行期间上传的工件。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Download artifact
#      uses: actions/download-artifact@v2
#      with:
#        name: app-apk
    - name: Cache
      uses: actions/cache@v2
      with:
        path: app/build/outputs
        key: outputs
    - run: ./gradlew uploadApk


